# Generated by Django 4.2.4 on 2023-12-01 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1000, verbose_name='Номер')),
                ('price', models.FloatField(default=5000.0, verbose_name='Цена')),
                ('info', models.TextField(max_length=250, verbose_name='Информация')),
                ('image', models.ImageField(default='audiences/default.jpg', upload_to='audiences', verbose_name='Фото')),
                ('corpus', models.TextField(max_length=20, verbose_name='Корпус')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, max_length=100, verbose_name='Статус')),
                ('date', models.DateField(default=datetime.datetime(2023, 12, 1, 19, 3, 40, 566208, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления')),
                ('moderator', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, max_length=100, verbose_name='Модератор')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 1, 19, 3, 40, 566208, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 12, 1, 19, 3, 40, 566208, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 12, 1, 19, 3, 40, 566208, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
