# Generated by Django 4.2.4 on 2023-12-13 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_bookingaudiences_options_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiences',
            name='name',
            field=models.CharField(default='501', max_length=1000, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 13, 37, 24, 33164, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 13, 37, 24, 33164, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 13, 37, 24, 33164, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 13, 37, 24, 33164, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
    ]
