# Generated by Django 4.2.7 on 2023-12-24 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_user_alter_booking_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='audiences',
            field=models.ManyToManyField(null=True, to='booking.audiences', verbose_name='Аудитории'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 15, 13, 23, 840211, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
